plugin:
    name: 'norotaro.firebase::lang.plugin.name'
    description: 'norotaro.firebase::lang.plugin.description'
    author: Norotaro
    icon: oc-icon-fire
    homepage: ''
permissions:
    norotaro.firebase.access_settings:
        tab: 'norotaro.firebase::lang.plugin.name'
        label: 'norotaro.firebase::lang.permissions.access_settings'
